Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main()
  File "main.py", line 38, in main
    jit_test.run()
  File "/scratch/bbc33/pycuda/cuda/ex3/matmul.py", line 30, in run
    self._dot()
  File "/scratch/bbc33/pycuda/cuda/ex3/matmul.py", line 68, in _dot
    self.__dot_kernel(self.A, self.B, self.C)
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/bbc33/anaconda3/envs/pycuda/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type none

File "matmul.py", line 60:
    def __dot_kernel(A, B, C): # private method (double underscore prefix)
        for i in range(C.shape[0]):
        ^

[1] During: typing of get attribute at /scratch/bbc33/pycuda/cuda/ex3/matmul.py (60)

File "matmul.py", line 60:
    def __dot_kernel(A, B, C): # private method (double underscore prefix)
        for i in range(C.shape[0]):
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

