Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 39, in main
    jit_np_test.verify(expected)
  File "/scratch/bbc33/pycuda/cuda/ex3/matmul.py", line 38, in verify
    raise AssertionError(f"{__name__}: Results do not match! Computed C:\n{self.C}\nExpected C:\n{expected}")
AssertionError: matmul: Results do not match! Computed C:
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Expected C:
[[ 0.4977397   0.6975193   0.77814549  0.66924852]
 [ 0.77210575  0.73251057  1.14156711  0.87076175]
 [ 0.36594081  0.67151809  0.74949634  0.79108834]
 [ 0.75876725  0.59265524  0.88289911  0.52124894]]
