Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 39, in main
    jit_np_test.verify(expected)
  File "/scratch/bbc33/pycuda/cuda/ex3/matmul.py", line 38, in verify
    raise AssertionError(f"{__name__}: Results do not match! Computed C:\n{self.C}\nExpected C:\n{expected}")
AssertionError: matmul: Results do not match! Computed C:
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Expected C:
[[ 1.0469836   0.86408281  0.64345163  0.61953825]
 [ 1.69104552  1.4829309   1.10830343  1.04784656]
 [ 1.62274432  1.42344356  1.03340614  1.2725656 ]
 [ 1.95334888  1.87253118  1.34888399  1.46175015]]
